version: '3.5'

services:
  mongo:
    image: mongo
    restart: 'no'
    env_file:
      - .env
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: 'no'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
    links:
      - mongo

  bibliogo:
    build: .
    command: /bin/sh -c "/bibliogo/entrypoint.sh"
    restart: "no"
    links:
      - mongo
    volumes:
      - .:/bibliogo
    env_file:
      - .env
    ports:
      - 3000:3000

volumes:
  mongodb:
